import { Router } from "express";

import addressRouter from "./address/address.router";
import addressesRouter from "./address/addresses.router";
import authRouter from "./auth/auth.router";
import cartRouter from "./cart/cart.router";
import categoriesRouter from "./category/categories.router";
import categoryRouter from "./category/category.router";
import deliveriesRouter from "./delivery/deliveries.router";
import deliveryRouter from "./delivery/delivery.router";
import discountRouter from "./discount/discount.router";
import discountsRouter from "./discount/discounts.router";
import healthCheckRouter from "./healthCheck/healthCheck.router";
import imageRouter from "./image/image.router";
import inventoryRouter from "./inventory/inventory.router";
import orderRouter from "./order/order.router";
import ordersRouter from "./order/orders.router";
import productRouter from "./product/product.router";
import productsRouter from "./product/products.router";
import roleRouter from "./role/role.router";
import rolesRouter from "./role/roles.router";
import shopRouter from "./shop/shop.router";
import shopsRouter from "./shop/shops.router";
import userRouter from "./user/user.router";
import usersRouter from "./user/users.router";
import warehouseRouter from "./warehouse/warehouse.router";
import warehousesRouter from "./warehouse/warehouses.router";

const router = Router();

router.use("/health-check", healthCheckRouter);
router.use("/auth", authRouter);
router.use("/user", userRouter);
router.use("/users", usersRouter);
router.use("/address", addressRouter);
router.use("/addresses", addressesRouter);
router.use("/cart", cartRouter);
router.use("/category", categoryRouter);
router.use("/categories", categoriesRouter);
router.use("/delivery", deliveryRouter);
router.use("/deliveries", deliveriesRouter);
router.use("/discount", discountRouter);
router.use("/discounts", discountsRouter);
router.use("/image", imageRouter);
router.use("/inventory", inventoryRouter);
router.use("/order", orderRouter);
router.use("/orders", ordersRouter);
router.use("/product", productRouter);
router.use("/products", productsRouter);
router.use("/role", roleRouter);
router.use("/roles", rolesRouter);
router.use("/shop", shopRouter);
router.use("/shops", shopsRouter);
router.use("/warehouse", warehouseRouter);
router.use("/warehouses", warehousesRouter);

export default router;
